name: Deploy README

on:
  workflow_dispatch:
  schedule:
    - cron: 0 */6 * * *
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 检出当前项目代码
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main
    # 配置好node环境
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    # 执行js命令    
    - name: Update YearBar.js
      run: |
          node ./src/progressBar.js
    - name: Commit Change & Push
      run: |
          git config user.name 'github actions'
          git config user.email '87641777+xucux@users.noreply.github.com'
          git commit -am "bot: update progressBar"
          git push
